repos:
  - repo: local
    hooks:
      - id: black
        name: Black formater
        entry: black --check
        language: system
        types: [python]
      - id: flake8
        name: Linter
        entry: flake
        language: system
        types: [python]
      - id: isort
        name: Sort imports
        entry: isort
        language: system
        types: [python]